
const API_BASE = 'https://script.google.com/macros/s/AKfycbxti4DHFkii-KBvBFkUal0Qy0wDQVX_v6HCiIl_-4lGrrZRinRQRVeNHRb11FBJz_Nc9Q/exec';
const $ = id => document.getElementById(id);
const num = v => { const n = parseFloat(v); return isNaN(n) ? null : n; };
const numOr0 = v => { const n = num(v); return n === null ? 0 : n; };
const isActiveRow = v => String(v).toLowerCase() === 'true';
const blank = v => (v === null || v === undefined || v === 0);
const fmtInt = v => blank(v) ? '' : Math.round(v).toLocaleString('en-US');
const fmtPct = v => blank(v) ? '' : v.toFixed(1);
const fmtWoi = v => blank(v) ? '' : v.toFixed(1);
const idle = () => '<span class="idle">·</span>';
const cssVar = k => getComputedStyle(document.documentElement).getPropertyValue(k).trim();
const clamp = (v,a,b) => Math.max(a, Math.min(b, v));
function seriesLabel(s){ if(!s) return 'Other'; if(s.indexOf('Business') === 0) return 'Business & Productivity'; return s; }
function seriesColorVar(s){ if(s === 'Gaming') return '--gaming'; if(s && s.indexOf('Business') === 0) return '--bp'; if(s === 'Handheld') return '--handheld'; return '--others'; }
function achCls(p){ if(p === null) return 'v-off'; if(p >= 85) return 'v-pos'; if(p >= 70) return 'v-warn'; return 'v-neg'; }
function woiCls(w){ if(w === null) return 'v-off'; if(w > 20) return 'v-neg'; if(w > 12) return 'v-warn'; return ''; }
function signCls(v){ if(v === null) return 'v-off'; return v > 0 ? 'v-pos' : 'v-neg'; }
const QW = 13;
const DEFAULTS = { year:null, quarter:null };
let periodLocked = false, periodTouched = false;
let fullData = [];
const filters = { year:new Set(), quarter:new Set(), salesRep:new Set(), channel:new Set(), series:new Set(), customer:new Set() };
const sort = { f:'actual', d:'desc' };
function currentPeriod(){ const d = new Date(); return { year:'Y'+d.getFullYear(), quarter:'Q'+(Math.floor(d.getMonth()/3)+1) }; }
function initDefaultPeriod(fromNetwork){
  if(periodLocked || periodTouched || !fullData.length) return;
  const combos = new Set(fullData.map(r => r.year_label+'|'+r.quarter_label));
  const cur = currentPeriod(); let y = cur.year, q = cur.quarter;
  if(!combos.has(y+'|'+q)){ const latest = [...combos].filter(Boolean).sort().pop(); if(latest){ const p = latest.split('|'); y = p[0]; q = p[1]; } }
  DEFAULTS.year = y; DEFAULTS.quarter = q; filters.year = new Set([y]); filters.quarter = new Set([q]);
  if(fromNetwork) periodLocked = true;
}
function quarterBounds(yl, ql){ const y = parseInt(String(yl).replace('Y',''),10), q = parseInt(String(ql).replace('Q',''),10); if(!y || !q) return null; return { start:new Date(y,(q-1)*3,1), end:new Date(y,q*3,0,23,59,59) }; }
function quarterClock(){
  if(filters.year.size !== 1 || filters.quarter.size !== 1) return null; const b = quarterBounds([...filters.year][0], [...filters.quarter][0]); if(!b) return null; const now = new Date();
  if(now < b.start) return { state:'future', wk:0, left:QW, pct:0 }; if(now > b.end) return { state:'closed', wk:QW, left:0, pct:100 };
  const days = (now-b.start)/86400000, total = (b.end-b.start)/86400000; const wk = clamp(Math.ceil(days/7), 1, QW);
  return { state:'live', wk, left:QW-wk, pct:clamp(days/total*100,0,100) };
}
function periodLabel(){ const ys = [...filters.year].map(v => v.replace('Y','')).sort(), qs = [...filters.quarter].sort(); if(ys.length === 1 && qs.length === 1) return ys[0]+' '+qs[0]; const y = ys.length === 0 ? 'All years' : (ys.length === 1 ? ys[0] : ys.length+' years'); const q = qs.length === 0 ? 'all quarters' : (qs.length === 1 ? qs[0] : qs.length+' quarters'); return y+' · '+q; }
async function fetchView(view, params){ const qs = new URLSearchParams(Object.assign({ view }, params||{}, { _ts:Date.now() })).toString(); const res = await fetch(API_BASE+'?'+qs, { cache:'no-store' }); const j = await res.json(); if(!j.ok) throw new Error(j.error_message || j.error || 'API error'); return j.rows; }
function toast(m){ const t = $('toast'); t.textContent = m; t.style.display = 'block'; setTimeout(() => t.style.display = 'none', 9000); }
window.addEventListener('error', e => toast('Script error: '+(e.message||e.error))); window.addEventListener('unhandledrejection', e => toast('Promise error: '+(e.reason && e.reason.message ? e.reason.message : e.reason)));
function cacheSet(k,v){ try{ localStorage.setItem(k,v); }catch(e){ try{ localStorage.removeItem(k); localStorage.setItem(k,v); }catch(e2){} } }
async function loadData(force){
  const KEY = 'msi_target_tracking_v3';
  if(!force){ try{ const c = JSON.parse(localStorage.getItem(KEY) || 'null'); if(c && c.data){ fullData = c.data; buildOptions(false); render(); stamp(c.ts, true); } }catch(e){} }
  $('btnRefresh').classList.add('busy');
  try{ fullData = await fetchView('target_tracking', {}); cacheSet(KEY, JSON.stringify({ data:fullData, ts:Date.now() })); stamp(Date.now(), false); buildOptions(true); render(); } catch(e){ console.error(e); toast('Could not load data: '+e.message); } finally{ $('btnRefresh').classList.remove('busy'); }
}
function stamp(ts, cached){ const s = new Date(ts).toLocaleString('en-GB', { day:'2-digit', month:'2-digit', hour:'2-digit', minute:'2-digit' }); $('stamp').textContent = (cached ? 'Cached ' : 'Updated ')+s; $('stamp').classList.toggle('stale', !!cached); }
function scope(rows){ return rows.filter(r => (!filters.year.size || filters.year.has(r.year_label)) && (!filters.quarter.size || filters.quarter.has(r.quarter_label)) && (!filters.salesRep.size || filters.salesRep.has(r.sales_rep)) && (!filters.channel.size || filters.channel.has(r.channel_type)) && (!filters.series.size || filters.series.has(r.series_group)) && (!filters.customer.size || filters.customer.has(r.customer))); }
const SECTIONS = [ { k:'salesRep', label:'Sales representative', dim:r => r.sales_rep || '—' }, { k:'channel',  label:'Channel type', dim:r => r.channel_type || '—' }, { k:'series',   label:'Product series', dim:r => r.series_group || '—' }, { k:'customer', label:'Customer', dim:r => r.customer || '—' } ];
function scopeExcept(except){ return fullData.filter(r => (!filters.year.size || filters.year.has(r.year_label)) && (!filters.quarter.size || filters.quarter.has(r.quarter_label)) && (except === 'salesRep' || !filters.salesRep.size || filters.salesRep.has(r.sales_rep)) && (except === 'channel'  || !filters.channel.size  || filters.channel.has(r.channel_type)) && (except === 'series'   || !filters.series.size   || filters.series.has(r.series_group)) && (except === 'customer' || !filters.customer.size || filters.customer.has(r.customer))); }
function histScopeExcept(except){ return fullData.filter(r => (except === 'salesRep' || !filters.salesRep.size || filters.salesRep.has(r.sales_rep)) && (except === 'channel'  || !filters.channel.size  || filters.channel.has(r.channel_type)) && (except === 'series'   || !filters.series.size   || filters.series.has(r.series_group)) && (except === 'customer' || !filters.customer.size || filters.customer.has(r.customer))); }
function aggregate(rows, keyFn){ const m = new Map(); rows.forEach(r => { const k = keyFn(r); if(!m.has(k)) m.set(k, { key:k, target:0, actual:0, sellOut:0, linTgt:0, linAct:0, soh:0, avgSo:0, ly:0, dgw:0, vsc:0, spc:0, oth:0, active:false }); const g = m.get(k); g.target += numOr0(r.dealers_target); g.actual += numOr0(r.sell_in_actual); g.sellOut += numOr0(r.sell_out_actual); g.linTgt += numOr0(r.linearity_target); g.linAct += numOr0(r.sell_in_linearity_actual); g.soh += numOr0(r.dealers_soh); g.avgSo += numOr0(r.avg_sellout_per_week); g.ly += numOr0(r.sell_in_last_year); g.dgw += numOr0(r.sell_in_dgw); g.vsc += numOr0(r.sell_in_vsc); g.spc += numOr0(r.sell_in_spc); g.oth += numOr0(r.sell_in_others); if(isActiveRow(r.is_active)) g.active = true; }); return [...m.values()].map(g => Object.assign(g, { ach: g.target > 0 ? g.actual/g.target*100 : null, lin: g.linTgt > 0 ? g.linAct/g.linTgt*100 : null, woi: g.avgSo > 0 ? g.soh/g.avgSo : null, yoy: g.ly > 0 ? (g.actual-g.ly)/g.ly*100 : null, gap: g.target > 0 ? g.target-g.actual : null })); }
function totals(rows){ const t = { sellIn:0, target:0, sellOut:0, linAct:0, linTgt:0, ly:0, soh:0, avgSo:0, dgw:0, vsc:0, spc:0, oth:0 }; rows.forEach(r => { t.sellIn += numOr0(r.sell_in_actual); t.target += numOr0(r.dealers_target); t.sellOut += numOr0(r.sell_out_actual); t.linAct += numOr0(r.sell_in_linearity_actual); t.linTgt += numOr0(r.linearity_target); t.ly += numOr0(r.sell_in_last_year); t.soh += numOr0(r.dealers_soh); t.avgSo += numOr0(r.avg_sellout_per_week); t.dgw += numOr0(r.sell_in_dgw); t.vsc += numOr0(r.sell_in_vsc); t.spc += numOr0(r.sell_in_spc); t.oth += numOr0(r.sell_in_others); }); t.ach = t.target > 0 ? t.sellIn/t.target*100 : null; t.lin = t.linTgt > 0 ? t.linAct/t.linTgt*100 : null; t.woi = t.avgSo > 0 ? t.soh/t.avgSo : null; t.yoy = t.ly > 0 ? (t.sellIn-t.ly)/t.ly*100 : null; t.gap = t.target > 0 ? t.target-t.sellIn : null; return t; }
const COVERAGE_FLOOR = 25;
function coverage(rows){ if(!rows.length) return null; const f = rows.filter(r => numOr0(r.sell_in_actual) > 0).length; return { filled:f, total:rows.length, pct:f/rows.length*100 }; }
function sparkIndex(keyFn, except){ const hist = histScopeExcept(except); const periods = [...new Set(hist.map(r => r.year_label+r.quarter_label))].sort().slice(-8); const idx = new Map(); hist.forEach(r => { const p = r.year_label+r.quarter_label, i = periods.indexOf(p); if(i === -1) return; const k = keyFn(r); if(!idx.has(k)) idx.set(k, new Array(periods.length).fill(0)); idx.get(k)[i] += numOr0(r.sell_in_actual); }); return { periods, idx }; }
function smoothSparkPath(vals){ if(!vals || vals.length < 2) return idle(); const w = 88, h = 18, max = Math.max.apply(null, vals); if(max <= 0) return idle(); const pts = vals.map((v,i) => ({ x: i/(vals.length-1)*w, y: h - 3 - (v/max)*(h-8) })); let d = 'M '+pts[0].x.toFixed(1)+' '+pts[0].y.toFixed(1); for(let i=1;i<pts.length;i++){ const cp1x = pts[i-1].x + (pts[i].x - pts[i-1].x)/2; const cp1y = pts[i-1].y; const cp2x = pts[i].x - (pts[i].x - pts[i-1].x)/2; const cp2y = pts[i].y; d += ' C '+cp1x.toFixed(1)+' '+cp1y.toFixed(1)+' '+cp2x.toFixed(1)+' '+cp2y.toFixed(1)+' '+pts[i].x.toFixed(1)+' '+pts[i].y.toFixed(1); } const lx = pts[pts.length-1].x, ly = pts[pts.length-1].y; return `<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" aria-hidden="true" style="display:block overflow:visible"><path d="${d}" fill="none" stroke="${cssVar('--ink-4')}" stroke-width="1.1" stroke-linejoin="round"/><circle cx="${lx.toFixed(1)}" cy="${ly.toFixed(1)}" r="1.8" fill="${cssVar('--accent')}"/></svg>`; }
function paceBar(ach, elapsed){ if(ach === null) return idle(); const w = 88, h = 6; const fw = clamp(ach,0,100)/100*w; const behind = elapsed !== null && (ach-elapsed) < -10; const col = behind ? cssVar('--accent') : cssVar('--bar'); const tick = elapsed === null ? '' : `<rect x="${(clamp(elapsed,0,100)/100*w-0.5).toFixed(1)}" y="-1.5" width="1" height="${h+3}" fill="${cssVar('--ink-2')}" rx="0.5"/>`; return `<svg width="${w}" height="${h+3}" viewBox="0 -1.5 ${w} ${h+3}" aria-hidden="true" style="display:block"><rect x="0" y="0" width="${w}" height="${h}" fill="${cssVar('--rule')}" rx="10"/><rect x="0" y="0" width="${fw.toFixed(1)}" height="${h}" fill="${col}" rx="10"/>${tick}</svg>`; }
function polar(cx,cy,r,f){ const a = Math.PI*(1-f); return [cx+r*Math.cos(a), cy-r*Math.sin(a)]; }
function arcD(cx,cy,r,f0,f1){ const [x0,y0] = polar(cx,cy,r,f0), [x1,y1] = polar(cx,cy,r,f1); return `M ${x0.toFixed(2)} ${y0.toFixed(2)} A ${r} ${r} 0 ${(f1-f0)>0.5?1:0} 1 ${x1.toFixed(2)} ${y1.toFixed(2)}`; }
function gauge(value, max){ const cx = 36, cy = 30, r = 24, sw = 4; const f = value === null ? 0 : clamp(value/max, 0, 1); const col = value === null ? cssVar('--ink-4') : value >= 85 ? cssVar('--pos') : value >= 70 ? cssVar('--warn') : cssVar('--accent'); return `<svg width="72" height="40" viewBox="0 0 72 40" role="img"><path d="${arcD(cx,cy,r,0,1)}" fill="none" stroke="${cssVar('--rule-2')}" stroke-width="${sw}" stroke-linecap="round"/><path d="${arcD(cx,cy,r,0,f)}" fill="none" stroke="${col}" stroke-width="${sw}" stroke-linecap="round"/><text x="${cx}" y="${cy-1}" text-anchor="middle" font-family="IBM Plex Mono, monospace" font-size="10.5" font-weight="500" fill="${cssVar('--ink-2)}">${value === null ? '–' : value.toFixed(1)+'%'}</text><text x="${cx}" y="${cy+11}" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" font-weight="700" fill="${cssVar('--ink-2)}" letter-spacing=".12em">ACHIEVE</text></svg>`; }
function dimTag(g, secKey){ const sw = secKey === 'series' ? `<span class="swatch" style="background:${cssVar(seriesColorVar(g.key))}"></span>` : ''; return sw + (secKey === 'series' ? seriesLabel(g.key) : g.key); }
function sortGroups(gs){ const col = COLS.find(c => c.f === sort.f); const mul = sort.d === 'asc' ? 1 : -1; gs.sort((a,b) => { if(col && col.t === 'str') return mul*String(a[sort.f]||'').localeCompare(String(b[sort.f]||'')); const av = a[sort.f] === null || a[sort.f] === undefined ? -Infinity : a[sort.f]; const bv = b[sort.f] === null || b[sort.f] === undefined ? -Infinity : b[sort.f]; return mul*(av-bv); }); }
function render(){ const rows = scope(fullData); const t = totals(rows); const clock = quarterClock(); $('period').textContent = periodLabel(); $('week').textContent = !clock ? '' : clock.state === 'live' ? 'W'+clock.wk+'/'+QW+' · '+clock.left+' left' : clock.state === 'closed' ? 'closed' : 'not started'; try{ renderRail(t, clock, rows); }catch(e){ console.error('rail', e); } try{ renderNotice(rows); }catch(e){ console.error('notice', e); } try{ renderLedger(clock); }catch(e){ console.error('ledger', e); toast('Render error: '+e.message); } }
function renderRail(t, clock, rows){ const req = (clock && clock.state === 'live' && clock.left > 0 && t.gap !== null && t.gap > 0) ? t.gap/clock.left : null; const cur = (clock && clock.wk > 0 && t.sellIn > 0) ? t.sellIn/clock.wk : null; const kpi = (k, v, s, cls) => `<div class="kpi"><div class="kpi-k">${k}</div><div class="kpi-v ${cls||''}">${v}</div><div class="kpi-s">${s||''}</div></div>`; $('rail').innerHTML = kpi('Achievement', t.ach === null ? '–' : t.ach.toFixed(1)+'%', `<span class="m">${fmtInt(t.sellIn)||0}</span> of <span class="m">${fmtInt(t.target)||0}</span>`, 'lead '+(t.ach===null?'':achCls(t.ach).replace('v-',''))) + kpi('Gap to target', t.gap === null ? '–' : fmtInt(Math.abs(t.gap)), t.gap === null ? 'no target' : (t.gap > 0 ? 'pcs to ship' : 'pcs over'), t.gap !== null && t.gap <= 0 ? 'pos' : '') + kpi('Req run-rate', req === null ? '–' : fmtInt(req), req === null ? '—' : 'pcs / week') + kpi('Run-rate', cur === null ? '–' : fmtInt(cur), cur === null ? '—' : 'pcs / week to date') + kpi('Sell out', fmtInt(t.sellOut) || '–', t.sellIn > 0 ? 'ratio <span class="m">'+(t.sellOut/t.sellIn).toFixed(2)+'</span>' : '—') + kpi('SOH', fmtInt(t.soh) || '–', 'pcs on hand') + kpi('Avg WOI', t.woi === null ? '–' : t.woi.toFixed(1), 'weeks of inventory', t.woi === null ? '' : woiCls(t.woi).replace('v-','')) + `<div class="rail-gauges"><div class="gz">${gauge(t.ach, 120)}<div class="gz-k">Achievement</div></div><div class="gz">${gauge(t.lin, 150)}<div class="gz-k">Linearity</div></div></div>`; }
function renderNotice(rows){ const c = coverage(rows); $('notice').innerHTML = (c && c.pct < COVERAGE_FLOOR) ? `<div>Sell-in has landed for only <b>${c.filled} of ${c.total}</b> rows (<b>${c.pct.toFixed(0)}%</b>) in ${periodLabel()}. Closed quarters run 53–80%. Achievement, pace and run-rate below are <b>not</b> a business result — the source has not caught up.</div>` : ''; }
function subRow(t, n, elapsed){ return `<tr class="sub"><td>Subtotal · ${n}</td><td></td><td class="num n">${fmtInt(t.target)}</td><td class="num n">${fmtInt(t.sellIn)}</td><td class="num n"><span class="${achCls(t.ach)}">${fmtPct(t.ach)||'–'}</span></td><td>${paceBar(t.ach, elapsed)}</td><td class="num n">${t.gap === null ? '' : fmtInt(t.gap)}</td><td class="num n">${fmtInt(t.dgw)}</td><td class="num n">${fmtInt(t.vsc)}</td><td class="num n">${fmtInt(t.spc)}</td><td class="num n">${fmtInt(t.oth)}</td><td class="num n">${fmtInt(t.soh)}</td><td class="num n"><span class="${woiCls(t.woi)}">${fmtWoi(t.woi)||'–'}</span></td><td class="num n"><span class="${signCls(t.yoy)}">${t.yoy === null ? '–' : (t.yoy>0?'+':'')+fmtPct(t.yoy)}</span></td></tr>`; }
function renderLedger(clock){ const elapsed = clock ? clock.pct : null; const colsRow = () => '<tr class="cols">'+COLS.map(c => { const on = sort.f === c.f; const ar = on ? `<span class="ar">${sort.d === 'asc' ? '↑' : '↓'}</span>` : ''; const label = c.f === 'key' ? 'Name' : c.l; return `<th scope="col" class="${c.cls.indexOf('n') > -1 ? 'n' : ''} ${on?'on':''}" ` + (c.t !== null ? `data-f="${c.f}" data-t="${c.t}"` : 'style="cursor:default"') + `>${label}${ar}</th>`; }).join('')+'</tr>'; let body = '', periods = null; SECTIONS.forEach(sec => { const rows = scopeExcept(sec.k); const groups = aggregate(rows, sec.dim); const si = sparkIndex(sec.dim, sec.k); if(!periods) periods = si.periods; groups.forEach(g => g.spark = si.idx.get(g.key) || null); sortGroups(groups); const t = totals(rows); const ctx = { elapsed, sec:sec.k }; const selN = filters[sec.k].size; const note = selN ? `<span class="sel-note">${selN} selected — other sections filtered</span>` : ''; body += `<tbody data-sec="${sec.k}">` + `<tr class="sec"><td colspan="${COLS.length}">${sec.label}<span class="cnt">${groups.length} rows</span>${note}</td></tr>` + colsRow() + (groups.length ? groups.map(g => `<tr data-k="${encodeURIComponent(g.key)}" class="${filters[sec.k].has(g.key)?'on':''}">` + COLS.map(c => `<td class="${c.cls}">${c.r(g, ctx)}</td>`).join('')+'</tr>').join('') + subRow(t, groups.length, elapsed) : `<tr><td colspan="${COLS.length}"><div class="empty">No rows for this selection.</div></td></tr>`) + '</tbody>'; }); $('ledger').innerHTML = body; const inScope = scope(fullData).length; $('meta').textContent = periodLabel()+' · '+inScope.toLocaleString('en-US')+' of '+fullData.length.toLocaleString('en-US')+' rows' + (periods && periods.length ? ' · trend '+periods[0].replace('Y','')+'→'+periods[periods.length-1].replace('Y','') : ''); $('ledger').querySelectorAll('tr.cols th[data-f]').forEach(th => th.addEventListener('click', () => { const f = th.dataset.f; if(sort.f === f) sort.d = sort.d === 'asc' ? 'desc' : 'asc'; else { sort.f = f; sort.d = th.dataset.t === 'str' ? 'asc' : 'desc'; } render(); })); $('ledger').querySelectorAll('tbody[data-sec]').forEach(tb => { const k = tb.dataset.sec; tb.querySelectorAll('tr[data-k]').forEach(tr => tr.addEventListener('click', () => { const v = decodeURIComponent(tr.dataset.k); if(filters[k].size === 1 && filters[k].has(v)) filters[k].clear(); else filters[k] = new Set([v]); selects[k].sync(); render(); })); }); }
const COLS = [ { f:'key', l:'', t:'str', cls:'name', r:(g,c) => dimTag(g, c.sec) }, { f:'_spark', l:'8Q sell-in', t:null, cls:'', r:g => smoothSparkPath(g.spark) }, { f:'target', l:'Target', t:'num', cls:'num n',r:g => fmtInt(g.target) || idle() }, { f:'actual', l:'Sell-in', t:'num', cls:'num n hi', r:g => fmtInt(g.actual) || idle() }, { f:'ach', l:'Ach %', t:'num', cls:'num n',r:g => g.ach === null ? idle() : `<span class="${achCls(g.ach)}">${fmtPct(g.ach)}</span>` }, { f:'_pace', l:'Pace', t:null, cls:'', r:(g,c) => paceBar(g.ach, c.elapsed) }, { f:'gap', l:'Gap', t:'num', cls:'num n',r:g => g.gap === null ? idle() : (g.gap > 0 ? fmtInt(g.gap) : `<span class="v-pos">${fmtInt(g.gap)}</span>`) }, { f:'dgw', l:'DGW', t:'num', cls:'num n muted', r:g => fmtInt(g.dgw) || idle() }, { f:'vsc', l:'VSC', t:'num', cls:'num n muted', r:g => fmtInt(g.vsc) || idle() }, { f:'spc', l:'SPC', t:'num', cls:'num n muted', r:g => fmtInt(g.spc) || idle() }, { f:'oth', l:'Oth', t:'num', cls:'num n muted', r:g => fmtInt(g.oth) || idle() }, { f:'soh', l:'SOH', t:'num', cls:'num n',r:g => fmtInt(g.soh) || idle() }, { f:'woi', l:'WOI', t:'num', cls:'num n',r:g => g.woi === null ? idle() : `<span class="${woiCls(g.woi)}">${fmtWoi(g.woi)}</span>` }, { f:'yoy', l:'YoY %', t:'num', cls:'num n',r:g => g.yoy === null ? idle() : `<span class="${signCls(g.yoy)}">${(g.yoy>0?'+':'')+fmtPct(g.yoy)}</span>` } ];
class Select{ constructor(id, key){ this.root = $(id); this.key = key; this.opts = []; this.btn = this.root.querySelector('.sel-btn'); this.val = this.root.querySelector('.v'); this.panel = this.root.querySelector('.sel-panel'); this.search = this.root.querySelector('.sel-search'); this.list = this.root.querySelector('.sel-list'); this.btn.addEventListener('click', e => { e.stopPropagation(); this.toggle(); }); if(this.search) this.search.addEventListener('input', () => this.paint()); document.addEventListener('click', e => { if(!this.root.contains(e.target)) this.panel.classList.remove('open'); }); } toggle(){ document.querySelectorAll('.sel-panel.open').forEach(p => { if(p !== this.panel) p.classList.remove('open'); }); this.panel.classList.toggle('open'); if(this.panel.classList.contains('open') && this.search) this.search.focus(); } setOptions(o){ this.opts = o; this.paint(); } label(v){ if(this.key === 'year') return String(v).replace('Y',''); if(this.key === 'series') return seriesLabel(v); return v; } changed(){ if(this.key === 'year' || this.key === 'quarter') periodTouched = true; this.sync(); render(); } paint(){ const q = this.search ? this.search.value.toLowerCase() : ''; const list = this.opts.filter(o => o.toLowerCase().includes(q)); const all = this.opts.length > 0 && this.opts.every(o => filters[this.key].has(o)); this.list.innerHTML = (this.opts.length ? `<label class="sel-opt sel-all"><input type="checkbox" data-all="1" ${all?'checked':''}>All</label>` : '') + (list.length ? list.map(o => `<label class="sel-opt"><input type="checkbox" data-v="${encodeURIComponent(o)}" ${filters[this.key].has(o)?'checked':''}>${this.label(o)}</label>`).join('') : '<div class="sel-none">No matches</div>'); const a = this.list.querySelector('[data-all]'); if(a) a.addEventListener('change', () => { if(a.checked) this.opts.forEach(o => filters[this.key].add(o)); else filters[this.key].clear(); this.paint(); this.changed(); }); this.list.querySelectorAll('input[data-v]').forEach(cb => cb.addEventListener('change', () => { const v = decodeURIComponent(cb.dataset.v); if(cb.checked) filters[this.key].add(v); else filters[this.key].delete(v); this.changed(); })); } sync(){ const n = filters[this.key].size; this.val.textContent = n === 0 ? 'All' : (n === 1 ? this.label([...filters[this.key]][0]) : n+' selected'); this.btn.classList.toggle('on', n > 0); this.paint(); } }
const selects = {};
function buildOptions(fromNetwork){ initDefaultPeriod(fromNetwork); const uniq = f => [...new Set(fullData.map(r => r[f]).filter(Boolean))].sort(); selects.year.setOptions(uniq('year_label')); selects.quarter.setOptions(uniq('quarter_label')); selects.salesRep.setOptions(uniq('sales_rep')); selects.channel.setOptions(uniq('channel_type')); selects.series.setOptions(uniq('series_group')); selects.customer.setOptions(uniq('customer')); Object.values(selects).forEach(s => s.sync()); }
function reset(){ periodTouched = true; filters.year = new Set(DEFAULTS.year ? [DEFAULTS.year] : []); filters.quarter = new Set(DEFAULTS.quarter ? [DEFAULTS.quarter] : []); filters.salesRep.clear(); filters.channel.clear(); filters.series.clear(); filters.customer.clear(); Object.values(selects).forEach(s => s.sync()); render(); }
(function theme(){ const t = localStorage.getItem('msi_theme_v3') || 'light'; document.documentElement.setAttribute('data-theme', t); $('btnTheme').textContent = t === 'dark' ? 'Light' : 'Dark'; $('btnTheme').addEventListener('click', () => { const n = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark'; document.documentElement.setAttribute('data-theme', n); localStorage.setItem('msi_theme_v3', n); $('btnTheme').textContent = n === 'dark' ? 'Light' : 'Dark'; render(); }); })();
selects.year = new Select('selYear','year'); selects.quarter = new Select('selQuarter','quarter'); selects.salesRep = new Select('selSalesRep','salesRep'); selects.channel = new Select('selChannel','channel'); selects.series = new Select('selSeries','series'); selects.customer = new Select('selCustomer','customer');
$('btnClear').addEventListener('click', reset); $('btnRefresh').addEventListener('click', () => loadData(true)); loadData(false);
